# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'anki_addon_exporter.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setEnabled(True)
        Dialog.resize(550, 320)
        Dialog.setMaximumSize(QtCore.QSize(550, 320))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Downloads/picturetopeople.org-78fa7fadd60dc6ffdec28b8183e03d0bddd7b0bf9484bf1b65.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Dialog.setWindowIcon(icon)
        Dialog.setAutoFillBackground(False)
        self.verticalLayoutWidget = QtWidgets.QWidget(Dialog)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 10, 521, 281))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.gridLayout.setObjectName("gridLayout")
        self.bt_Export = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_Export.setObjectName("bt_Export")
        self.gridLayout.addWidget(self.bt_Export, 0, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout)
        self.textEdit = QtWidgets.QTextEdit(self.verticalLayoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.bt_copy = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.bt_copy.setObjectName("bt_copy")
        self.verticalLayout.addWidget(self.bt_copy)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(440, 300, 81, 16))
        self.label.setObjectName("label")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Anki Add-On Number Exporter"))
        self.bt_Export.setText(_translate("Dialog", "Export"))
        self.bt_copy.setText(_translate("Dialog", "Copy All"))
        self.label.setText(_translate("Dialog", "by Luckas H."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
